SELECT * FROM dbo.Customers
SELECT * FROM dbo.CustomerType
SELECT * FROM dbo.EmployeePA
SELECT * FROM dbo.EmployeePerSubsidiary
SELECT * FROM dbo.Employees
SELECT * FROM dbo.EmployeeType
SELECT * FROM dbo.Errors
SELECT * FROM dbo.Food
SELECT * FROM dbo.GreatCombinations
SELECT * FROM dbo.LiqueurInfo
SELECT * FROM dbo.Liqueurs
SELECT * FROM dbo.PaymentTypes
SELECT * FROM dbo.Schedules
SELECT * FROM dbo.Shippings
SELECT * FROM dbo.Stock
SELECT * FROM dbo.Subsidiary
SELECT * FROM dbo.TaxesReport
SELECT * FROM dbo.Transactions
SELECT * FROM dbo.TransactionType
SELECT * FROM dbo.Users